### ISSUE TITLE
Kibana in Visualize data

### ISSUE THREAD

**Issue by aravindputrevu** [datastacktv/data-engineer-roadmap#12]
It'd be great if you could add Kibana to visualize data. One of the popular components in ELK stack. 

https://github.com/elastic/kibana

**Comment by alexandraabbas** [comment]
Hey @aravindputrevu, thanks for the suggestion! It was in the list originally but I removed it as I listed too many tools I felt. I checked and Kibana has the same popularity as Grafana based on [Google trends](https://trends.google.com/trends/explore?geo=US&q=kibana,grafana,looker) to I'll add it in version 1.1

**Comment by aravindputrevu** [comment]
Thank you 😊
