### ISSUE TITLE
Lightweight markup languages

### ISSUE THREAD

**Issue by epogrebnyak** [datastacktv/data-engineer-roadmap#13]
Somewhere early in the tree maybe mention markdown? Useful for documentation, github issues, Jupyter.

**Comment by alexandraabbas** [comment]
Hey there, that's a good idea! I might include that in CS fundamentals, that seems the most relevant section.

**Comment by epogrebnyak** [comment]
version control (git), markdown, text editor all seem a good fit for a new Terminal section. You can easyli decouple that from CS block.

I really like how computers work as a starting point:
- how computers work
- how does internet work
- operation system basics (maybe add this, learning about file system)

Feel free to adopt at your discretion, the chart already is very useful and thought-stimulating!

**Comment by alexandraabbas** [comment]
Yes, good point. I'll definitely consider your suggestion!

**Comment by epogrebnyak** [comment]
In current version git is in the same cloud at how computers and Internet work, which suggests it is super-fundimental. May decouple git form that cloud? That would leave how computer and how intenet works in one area and git in another. Perhaps that is a better stand-alone place for git.
