### ISSUE TITLE
Suggestion: Data Modeling & Execution Engine

### ISSUE THREAD

**Issue by YudaBorochov** [datastacktv/data-engineer-roadmap#16]
Hi everyone,
I LOVE THIS. Thanks!
I would humbly add, from my experience, 3 domains:
1. Data modeling techniques. 
These are critical to really own DWHing and data eng in general and would include:
- Kimbal/Inmon classical approaches as base.
- Snowflake/Star as more advanced views.
- Data Vault 2.0

2. The subdomain of database admin/understanding that is Execution Engine tweaking, that would hold:
- Execution plans and hints
- Indexes to their different types
- TOP 3-5 DB vendor's proprietary tricks for this domain.

3. ETL & ELT concepts in different scales and velocity. When to use which and why, etc.

**Comment by alexandraabbas** [comment]
Hi @YudaBorochov, thank you for these insights! I'll definitely consider adding these to the next version of the roadmap.
