### ISSUE TITLE
Which Mind Map app?

### ISSUE THREAD

**Issue by RamanHacks** [datastacktv/data-engineer-roadmap#19]
Can I ask which mind map app you used to create this beautiful outline? It's simply awesome! <3
BTW the structure and content of your course is refreshing to say the least. Just purchased your annual membership. Looking forward to more such great content.

**Comment by QAInsights** [comment]
I guess its https://balsamiq.com/ @RamanHacks

**Comment by alexandraabbas** [comment]
Hey @RamanHacks, I'm so glad you like the roadmap and my course as well! I used [Figma](https://www.figma.com/) to design the roadmap. It's a UI design and prototyping tool.

**Comment by SoftwareEngineeringHygiene** [comment]
@alexandraabbas your awesome work inspired me to create a tool which can translate markdown text to a visually similar graph, thanks👍
