### ISSUE TITLE
Tech Stack too Overwhelming

### ISSUE THREAD

**Issue by Better-Boy** [datastacktv/data-engineer-roadmap#21]
Looking at the roadmap it's too overwhelming to see so many frameworks, technologies to learn.

My suggestion is to divide the technologies horizontally and vertically with years of experience. This would narrow down the roadmap or give a clear road map than just mentioning the tech stack. Along with the division, mention the projects to be made for the corresponding years of experience. 

The above is solely my opinion.

**Comment by KoeSystems** [comment]
This roadmap is similar to the famous "Developer roadmap" and "DevOps roadmap", both as complex and overwhelming as this. However, I would say the goal is to show a broad idea of everything you could learn about the topic, nobody needs to learn all that stuff and I really think that just very few humans master all those frameworks and technologies.

**Comment by alexandraabbas** [comment]
Hi there, yes I agree with @KoeSystems this roadmap tries to give a comprehensive picture of the data engineering landscape and potentially guide you with your studies by organising every available tech on a single chart. Although, I got this feedback from elsewhere as well so I might create a beginner version of the roadmap which helps aspiring data engineers prioritise which technologies to learn next and what are the best available learning resources.
