### ISSUE TITLE
Math and Statistics should be added

### ISSUE THREAD

**Issue by KoeSystems** [datastacktv/data-engineer-roadmap#22]
I know this is Data Engineer roadmap and not Data Science roadmap, however, I still think that Maths and Statistics should have its own box in the roadmap ( despite it could be included in the "Fundamentals" ).

Being a Data Engineer without enough math and statistics knowledge is considered as "Danger Zone" by Drew Conway’s diagram http://drewconway.com/zia/2013/3/26/the-data-science-venn-diagram

<img width="842" alt="ds_danger_zone" src="https://user-images.githubusercontent.com/4624589/95387919-bf074f80-08f1-11eb-86f4-ea7ebfb9d52b.png">

Other than that, **your roadmap is awesome** @alexandraabbas, thanks a lot.

**Comment by alexandraabbas** [comment]
Hi @KoeSystems, I think that's a great point! I'll definitely consider including Maths and Statistics under fundamentals in the next version. I'm glad you like the roadmap! 🙌
