### ISSUE TITLE
ClickHouse should be added to the "Data warehouses" section

### ISSUE THREAD

**Issue by alexey-milovidov** [datastacktv/data-engineer-roadmap#24]
https://github.com/ClickHouse/ClickHouse

**Comment by vickyshah129** [comment]
MemSQL/SingleStore is the best for pipelines, data warehouse and analytics. One stop shop for all. Consider that too

**Comment by alexandraabbas** [comment]
Hey there, thanks for the suggestion. I see many ppl upvoted your comment. I'll def include ClickHouse in the 2021 version. Thanks a lot!
