### ISSUE TITLE
Cloud Basics

### ISSUE THREAD

**Issue by sonusourabh** [datastacktv/data-engineer-roadmap#25]
As we are in cloud era, it's good to have knowledge on basic Cloud Architecture and common services from AWS/Azure etc.

I see you did mention a few cloud based tools, but it's good to have basic understanding of cloud services and how they are co related. A section named "Cloud fundamentals" maybe. 

What do you think?

Cheers!

**Comment by alexandraabbas** [comment]
I think that makes sense. I'll include that in the 2021 version (coming out soon). Thanks for the suggestion!
