### ISSUE TITLE
digdag

### ISSUE THREAD

**Issue by chapmanjacobd** [datastacktv/data-engineer-roadmap#3]
digdag is a nice workflow scheduler. much easier to setup than airflow

**Comment by alexandraabbas** [comment]
Hey @chapmanjacobd, thanks for the suggestion! I'll look into it and add it to workflow schedulers if it fits in 😊

**Comment by alexandraabbas** [comment]
Hey there, I looked into [digdag](https://www.digdag.io/). It's a great project, very promising! Although, this roadmap aims to include only the essential, most popular tools from the data engineering landscape. I don't wanna overwhelm people with too many tools. I'll post digdag on our [Twitter](https://twitter.com/datastacktv) though. Closing this issue for now.
