### ISSUE TITLE
Data Processing Architectures 

### ISSUE THREAD

**Issue by brayanjuls** [datastacktv/data-engineer-roadmap#31]
Hello! congratulations for such an awesome roadmap, I think a data engineer should know about lambda architecture and kappa architecture. I think those are base architectures to start building custom data processing architectures for specific problems.  Here are some resources: 
* https://milinda.pathirage.org/kappa-architecture.com/
* http://lambda-architecture.net/

**Comment by alexandraabbas** [comment]
Hey @brayanjuls - thanks for the suggestion! Definitely, I agree. I'll include these in the 2021 version.
