### ISSUE TITLE
Suggestion: replace Pulumi with the AWS CDK

### ISSUE THREAD

**Issue by knowsuchagency** [datastacktv/data-engineer-roadmap#4]
Great project! I would suggest replacing Pulumi with the AWS CDK https://github.com/aws/aws-cdk. Its variants, cdk8s and cdk for terraform already have incredible utility for how long the projects have existed and in my opinion, the cdk is the dominant player in the Infrastructure as Code space

**Comment by alexandraabbas** [comment]
Hey @knowsuchagency - thanks for the suggestion! Someone else on Reddit suggested replacing AWS CloudFormation with AWS CDK instead. Why would you replace Pulumi?

**Comment by knowsuchagency** [comment]
I think it's more appropriate to replace Pulumi because Pulumi is a tool for defining infrastructure programmatically using a programming language like Python which is the same space the CDK occupies. Also, the CDK family of libraries now not only supports cloudformation as the backend, but terraform, and k8s manifests.

**Comment by alexandraabbas** [comment]
I see then I'll add AWS CDK as an extra so Pulumi is still there as a cloud agnostic option.

**Comment by knowsuchagency** [comment]
Sounds good, but I would add that since the cdk family of libraries includes HCL and k8s manifests, simply replacing Pulumi with the CDK doesn't mean exclude other clouds besides AWS
