### ISSUE TITLE
Add GitLab Pipelines to CI/CD

### ISSUE THREAD

**Issue by yanniskatsaros** [datastacktv/data-engineer-roadmap#44]
Hey there,

Thanks for putting together this awesome resource! I’d strongly suggest adding GitLab Pipelines to the CI/CD section. It’s an extremely useful platform and is actually what competitively prompted GitHub Actions to emerge, as far as I know.

Hope this helps!

**Comment by alexandraabbas** [comment]
Thanks, I'm glad you like it! Good point, I used GitLab Pipelines myself previously and I liked it a lot. I'll add it to the image next time I update it.

**Comment by nialloriordan** [comment]
Drone and CircleCI are two other popular CI/CD tools. I don't think Jenkins should be considered a modern DE tool.
