### ISSUE TITLE
Which BPM would you suggest

### ISSUE THREAD

**Issue by Sunil6591** [datastacktv/data-engineer-roadmap#5]
So all application have business processes, I saw you mentioned workflow scheduling but can that also be used for bpm kind of system

**Comment by alexandraabbas** [comment]
Hey there, not sure what you mean. Can you elaborate?

**Comment by Sunil6591** [comment]
So if order processing workflow then it goes like this - 
Order is placed -> System auto confirms based on same rules -> Auto checks inventory -> If inventory ok -> fulfil the order
Workflows like these where each task has a set of rules and state. E.g. https://camunda.com/ is one bpm i know.
So system like these if you know and can include in your diagram.
btw - its awesome diagrammatic representation, thanks for that!!

**Comment by alexandraabbas** [comment]
In theory Apache Airflow could be used for a workflow like this but probably would be too slow. I'll have a look at the tool you sent and include it if relevant. Thanks very much!
