### ISSUE TITLE
AWS Cloud Formation as a general recommendation

### ISSUE THREAD

**Issue by andrewfonseca** [datastacktv/data-engineer-roadmap#6]
AWS Cloud Formation as a general recommendation in my opinion doesn't make sense. I see Terraform with much more usage and bigger community, plus it is cloud agnostic.

**Comment by alexandraabbas** [comment]
Hey @andrewfonseca, I guess that makes sense as AWS CloudFormation only applies to AWS users. I'll update that soon. Thanks for the suggestion!
